### ISSUE TITLE
Compression ratio float numbers

### ISSUE THREAD

**Issue by FrantisekPostl** [PisaJan/data-series-compression#1]
If i set compression ration to 1.5 i get same result as if i set ratio to 2. It would be nice, if float numbers  would be supported.

**Comment by PisaJan** [comment]
It seems, that there is no issue with float compression ratios - covered by new test in:
https://github.com/PisaJan/data-series-compression/commit/7610124fbed34dba06368c71b15e65bf69a13b8f

I will close this for now, feel free to reopen issue with more informations if the problem stands.
